on:
  workflow_dispatch:
  schedule:
    - cron: '45 18 1,7,13,19,25 * *'


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: li1ht2ay/it1h-d4@cron
        with:
          token: ${{ secrets.token }}
