on:
  workflow_dispatch:
  schedule:
    - cron: '45 18 1,5,9,13,17,21,25,29 * *'


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: li1ht2ay/it1h-d4@cron
        with:
          token: ${{ secrets.token }}
